version: "3.7"
services:
  db-1:
    image: maximilianoteruel/mariadb:dev
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-1_data:/var/lib/mysql
      - db-1_backup:/usr/src/app/backup

  db-2:
    image: maximilianoteruel/mariadb:dev
    ports:
      - "23306:3306"
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_ROOT_PASSWORD=root
      - CRON_DB_DUMP=40_2_15_*_*
      - CRON_DB=10_2_*_*_*
    volumes:
      - db-2_data:/var/lib/mysql
      - db-2_backup:/usr/src/app/backup

  db-3:
    image: maximilianoteruel/mariadb:dev
    ports:
      - "33306:3306"
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_ROOT_PASSWORD=root
      - BACKUP_DISABLED=1
    volumes:
      - db-3_data:/var/lib/mysql

volumes:
  db-1_data:
  db-1_backup:
  db-2_data:
  db-2_backup:
  db-3_data:
